image: julia:1.4

before_script:
  - apt-get -qq update; apt-get -y install git

benchmarking:
  script:
    - git clone https://github.com/ProofOfConceptForJuliSmoothOptimizers/poc_jenkins_julia.git
    - cd poc_jenkins_julia
    - julia krylov_CI.jl
    - julia send_benchmarks_to_pr.jl -r poc_jenkins_julia -p 16

test:
  script:
    - julia krylov_test.jl
